language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - TEST_DIR=mobile
  - TEST_DIR=web
script: 
  - cd $TEST_DIR
  - npm install
  - npm test
notifications:
    slack: diamond-devs:idRzMleTGDetsZaoASgEalL1